### ISSUE TITLE
Add an executable to the releases section

### ISSUE THREAD

**Issue by calebmeyer** [jphellemons/GandalfSax#3]
You mention in the readme that you can run this from the executable, but there are no instructions for generating the executable. It would be great if it were included in release 1.0

**Comment by pedrofracassi** [comment]
Yes please

**Comment by jphellemons** [comment]
https://github.com/jphellemons/GandalfSax/releases/download/0.1/publish.zip

**Comment by pedrofracassi** [comment]
Thanks!
